// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59ihl6FQOv5cbDpUwwyh-DCtuCq8YdZ4',
    appId: '1:1071993420986:web:4fb8708c057829cc98d683',
    messagingSenderId: '1071993420986',
    projectId: 'we-the-artists',
    authDomain: 'we-the-artists.firebaseapp.com',
    storageBucket: 'we-the-artists.firebasestorage.app',
    measurementId: 'G-ZHEXS3MEP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY36ZCR24kAHgQYBcGqz-xIzHHWffOnRg',
    appId: '1:1071993420986:android:5d26fcdc62691c3398d683',
    messagingSenderId: '1071993420986',
    projectId: 'we-the-artists',
    storageBucket: 'we-the-artists.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwiOj0B6N7OKTUszBAAZBLMUG57WhEGKc',
    appId: '1:1071993420986:ios:f5a797e3766ac6a898d683',
    messagingSenderId: '1071993420986',
    projectId: 'we-the-artists',
    storageBucket: 'we-the-artists.firebasestorage.app',
    iosBundleId: 'com.example.weTheArtists',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwiOj0B6N7OKTUszBAAZBLMUG57WhEGKc',
    appId: '1:1071993420986:ios:f5a797e3766ac6a898d683',
    messagingSenderId: '1071993420986',
    projectId: 'we-the-artists',
    storageBucket: 'we-the-artists.firebasestorage.app',
    iosBundleId: 'com.example.weTheArtists',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD59ihl6FQOv5cbDpUwwyh-DCtuCq8YdZ4',
    appId: '1:1071993420986:web:9ede5212c07753a298d683',
    messagingSenderId: '1071993420986',
    projectId: 'we-the-artists',
    authDomain: 'we-the-artists.firebaseapp.com',
    storageBucket: 'we-the-artists.firebasestorage.app',
    measurementId: 'G-JRBM08MXHG',
  );
}
